#!/bin/sh
# Materialize iris.toml from environment at container start.
# Keeps credentials out of the image; iris resolves secret values
# from env vars declared in the config (token = { env = "..." }).
#
# Storage/audit locations are env-driven (IRIS_ATTACHMENT_DIR /
# IRIS_AUDIT_DIR), set in the Dockerfile — NOT config sections.
set -eu

CONF="${IRIS_CONFIG:-/etc/iris/iris.toml}"
mkdir -p "$(dirname "$CONF")"

PROVIDERS="${IRIS_ENABLED_PROVIDERS:-mock}"

# A fully-formed config mounted at /etc/iris/iris.mounted.toml wins.
if [ -f /etc/iris/iris.mounted.toml ]; then
  echo "Using mounted iris config." >&2
  cp /etc/iris/iris.mounted.toml "$CONF"
  exec "$@"
fi

{
  echo "# Generated by docker-entrypoint.sh — do not edit in place."
  echo
} > "$CONF"

for p in $(echo "$PROVIDERS" | tr ',' ' '); do
  echo "Enabling provider: $p" >&2
  case "$p" in
    mock)
      cat >> "$CONF" <<'EOF'
[providers.mock]
enabled = true

[providers.mock.credentials]
mode = "development"
EOF
      ;;
    telegram)
      cat >> "$CONF" <<'EOF'

[providers.telegram]
enabled = true

[providers.telegram.credentials]
bot_token = { env = "TELEGRAM_BOT_TOKEN" }
EOF
      ;;
    email)
      # All six keys are required (required() in email.rs); no defaults.
      # Set every IRIS_EMAIL_* env var or the provider fails startup.
      cat >> "$CONF" <<'EOF'

[providers.email]
enabled = true

[providers.email.credentials]
imap_host = { env = "IRIS_EMAIL_IMAP_HOST" }
imap_port = { env = "IRIS_EMAIL_IMAP_PORT" }
smtp_host = { env = "IRIS_EMAIL_SMTP_HOST" }
smtp_port = { env = "IRIS_EMAIL_SMTP_PORT" }
username = { env = "IRIS_EMAIL_USERNAME" }
password = { env = "IRIS_EMAIL_PASSWORD" }
EOF
      ;;
    sms)
      # SSH-bridge SMS provider: ssh_host required, phone_number used
      # for sender mapping.
      cat >> "$CONF" <<'EOF'

[providers.sms]
enabled = true

[providers.sms.credentials]
ssh_host = { env = "IRIS_SMS_SSH_HOST" }
phone_number = { env = "IRIS_SMS_PHONE_NUMBER" }
EOF
      ;;
    *)
      echo "Unknown provider '$p' — skipping. Add its block to the entrypoint or mount a full config at /etc/iris/iris.mounted.toml" >&2
      ;;
  esac
done

exec "$@"
